// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 587978194;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__dto__color_dto_to_rgb_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "color_dto_to_rgb",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::dto::ColorDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::dto::ColorDto::to_rgb(api_that))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__core_version_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "core_version",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::image_api::core_version())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__list_presets_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_presets",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::image_api::list_presets())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__make_preview_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "make_preview",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_filename = <Option<String>>::sse_decode(&mut deserializer);
            let api_options = <crate::api::dto::ProcessOptionsDto>::sse_decode(&mut deserializer);
            let api_max_side = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::core::error::PicProError>((move || {
                    let output_ok = crate::api::image_api::make_preview(
                        api_bytes,
                        api_filename,
                        api_options,
                        api_max_side,
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__probe_image_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "probe_image",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_filename = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::core::error::PicProError>((move || {
                    let output_ok = crate::api::image_api::probe_image(api_bytes, api_filename)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__process_batch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_batch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_items = <Vec<crate::api::dto::BatchItemDto>>::sse_decode(&mut deserializer);
            let api_options = <crate::api::dto::ProcessOptionsDto>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::dto::BatchProgressDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::image_api::process_batch(api_items, api_options, api_sink);
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__process_image_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_image",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_filename = <Option<String>>::sse_decode(&mut deserializer);
            let api_options = <crate::api::dto::ProcessOptionsDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::core::error::PicProError>((move || {
                    let output_ok =
                        crate::api::image_api::process_image(api_bytes, api_filename, api_options)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__process_image_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_image_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_options = <crate::api::dto::ProcessOptionsDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::core::error::PicProError>((move || {
                    let output_ok =
                        crate::api::image_api::process_image_file(api_path, api_options)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_api__standard_backgrounds_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "standard_backgrounds",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::image_api::standard_backgrounds())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::dto::BatchProgressDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::dto::BackgroundChoiceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_color = <crate::api::dto::ColorDto>::sse_decode(deserializer);
        return crate::api::dto::BackgroundChoiceDto {
            name: var_name,
            color: var_color,
        };
    }
}

impl SseDecode for crate::api::dto::BackgroundDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_color = <crate::api::dto::ColorDto>::sse_decode(deserializer);
        let mut var_tolerance = <Option<f32>>::sse_decode(deserializer);
        let mut var_featherPx = <Option<u32>>::sse_decode(deserializer);
        let mut var_decontaminate = <Option<bool>>::sse_decode(deserializer);
        let mut var_edgeOffset = <Option<f32>>::sse_decode(deserializer);
        let mut var_smoothAlpha = <Option<bool>>::sse_decode(deserializer);
        return crate::api::dto::BackgroundDto {
            color: var_color,
            tolerance: var_tolerance,
            feather_px: var_featherPx,
            decontaminate: var_decontaminate,
            edge_offset: var_edgeOffset,
            smooth_alpha: var_smoothAlpha,
        };
    }
}

impl SseDecode for crate::api::dto::BatchItemDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
        let mut var_filename = <Option<String>>::sse_decode(deserializer);
        return crate::api::dto::BatchItemDto {
            id: var_id,
            bytes: var_bytes,
            filename: var_filename,
        };
    }
}

impl SseDecode for crate::api::dto::BatchProgressDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_index = <u32>::sse_decode(deserializer);
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_done = <u32>::sse_decode(deserializer);
        let mut var_total = <u32>::sse_decode(deserializer);
        let mut var_succeeded = <u32>::sse_decode(deserializer);
        let mut var_failed = <u32>::sse_decode(deserializer);
        let mut var_result = <Option<crate::api::dto::ProcessResultDto>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::dto::BatchProgressDto {
            index: var_index,
            id: var_id,
            done: var_done,
            total: var_total,
            succeeded: var_succeeded,
            failed: var_failed,
            result: var_result,
            error: var_error,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::dto::ColorDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_red = <u32>::sse_decode(deserializer);
        let mut var_green = <u32>::sse_decode(deserializer);
        let mut var_blue = <u32>::sse_decode(deserializer);
        return crate::api::dto::ColorDto {
            red: var_red,
            green: var_green,
            blue: var_blue,
        };
    }
}

impl SseDecode for crate::api::dto::CompressDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_targetBytes = <Option<u64>>::sse_decode(deserializer);
        let mut var_maxLongSide = <Option<u32>>::sse_decode(deserializer);
        let mut var_qualityMax = <Option<u32>>::sse_decode(deserializer);
        let mut var_qualityFloor = <Option<u32>>::sse_decode(deserializer);
        let mut var_minLongSide = <Option<u32>>::sse_decode(deserializer);
        let mut var_jpegNoChromaSubsampling = <Option<bool>>::sse_decode(deserializer);
        let mut var_pngBestCompression = <Option<bool>>::sse_decode(deserializer);
        return crate::api::dto::CompressDto {
            target_bytes: var_targetBytes,
            max_long_side: var_maxLongSide,
            quality_max: var_qualityMax,
            quality_floor: var_qualityFloor,
            min_long_side: var_minLongSide,
            jpeg_no_chroma_subsampling: var_jpegNoChromaSubsampling,
            png_best_compression: var_pngBestCompression,
        };
    }
}

impl SseDecode for crate::api::dto::CropDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_presetId = <Option<String>>::sse_decode(deserializer);
        let mut var_rect = <Option<crate::api::dto::CropRectDto>>::sse_decode(deserializer);
        let mut var_outWidth = <Option<u32>>::sse_decode(deserializer);
        let mut var_outHeight = <Option<u32>>::sse_decode(deserializer);
        let mut var_verticalAnchor = <Option<f32>>::sse_decode(deserializer);
        return crate::api::dto::CropDto {
            preset_id: var_presetId,
            rect: var_rect,
            out_width: var_outWidth,
            out_height: var_outHeight,
            vertical_anchor: var_verticalAnchor,
        };
    }
}

impl SseDecode for crate::api::dto::CropRectDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <f32>::sse_decode(deserializer);
        let mut var_y = <f32>::sse_decode(deserializer);
        let mut var_width = <f32>::sse_decode(deserializer);
        let mut var_height = <f32>::sse_decode(deserializer);
        return crate::api::dto::CropRectDto {
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::dto::ImageInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_format = <String>::sse_decode(deserializer);
        let mut var_formatName = <String>::sse_decode(deserializer);
        let mut var_frameCount = <u32>::sse_decode(deserializer);
        let mut var_byteSize = <u64>::sse_decode(deserializer);
        let mut var_sourceSupportsAlpha = <bool>::sse_decode(deserializer);
        let mut var_sourceSupportsAnimation = <bool>::sse_decode(deserializer);
        return crate::api::dto::ImageInfoDto {
            width: var_width,
            height: var_height,
            format: var_format,
            format_name: var_formatName,
            frame_count: var_frameCount,
            byte_size: var_byteSize,
            source_supports_alpha: var_sourceSupportsAlpha,
            source_supports_animation: var_sourceSupportsAnimation,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::dto::BackgroundChoiceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::dto::BackgroundChoiceDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::dto::BatchItemDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::dto::BatchItemDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::dto::ColorDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::dto::ColorDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::dto::PresetDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::dto::PresetDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dto::BackgroundDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dto::BackgroundDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<bool>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dto::ColorDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dto::ColorDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dto::CompressDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dto::CompressDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dto::CropDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dto::CropDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dto::CropRectDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dto::CropRectDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dto::ProcessResultDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dto::ProcessResultDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::core::error::PicProError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::UnknownFormat(var_field0);
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::UnsupportedFormat(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::Decode(var_field0);
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::Encode(var_field0);
            }
            4 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::Svg(var_field0);
            }
            5 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::Io(var_field0);
            }
            6 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::TargetUnreachable(var_field0);
            }
            7 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::core::error::PicProError::InvalidArgument(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::dto::PresetDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_category = <String>::sse_decode(deserializer);
        let mut var_categoryName = <String>::sse_decode(deserializer);
        let mut var_widthMm = <f32>::sse_decode(deserializer);
        let mut var_heightMm = <f32>::sse_decode(deserializer);
        let mut var_widthPx = <u32>::sse_decode(deserializer);
        let mut var_heightPx = <u32>::sse_decode(deserializer);
        let mut var_dpi = <u32>::sse_decode(deserializer);
        let mut var_backgroundNames = <Vec<String>>::sse_decode(deserializer);
        let mut var_backgroundColors = <Vec<crate::api::dto::ColorDto>>::sse_decode(deserializer);
        let mut var_note = <String>::sse_decode(deserializer);
        return crate::api::dto::PresetDto {
            id: var_id,
            name: var_name,
            category: var_category,
            category_name: var_categoryName,
            width_mm: var_widthMm,
            height_mm: var_heightMm,
            width_px: var_widthPx,
            height_px: var_heightPx,
            dpi: var_dpi,
            background_names: var_backgroundNames,
            background_colors: var_backgroundColors,
            note: var_note,
        };
    }
}

impl SseDecode for crate::api::dto::ProcessOptionsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputFormat = <Option<String>>::sse_decode(deserializer);
        let mut var_crop = <Option<crate::api::dto::CropDto>>::sse_decode(deserializer);
        let mut var_background = <Option<crate::api::dto::BackgroundDto>>::sse_decode(deserializer);
        let mut var_compress = <Option<crate::api::dto::CompressDto>>::sse_decode(deserializer);
        let mut var_flattenColor = <Option<crate::api::dto::ColorDto>>::sse_decode(deserializer);
        let mut var_svgRenderWidth = <Option<u32>>::sse_decode(deserializer);
        return crate::api::dto::ProcessOptionsDto {
            output_format: var_outputFormat,
            crop: var_crop,
            background: var_background,
            compress: var_compress,
            flatten_color: var_flattenColor,
            svg_render_width: var_svgRenderWidth,
        };
    }
}

impl SseDecode for crate::api::dto::ProcessResultDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_format = <String>::sse_decode(deserializer);
        let mut var_formatName = <String>::sse_decode(deserializer);
        let mut var_sourceFormatName = <String>::sse_decode(deserializer);
        let mut var_quality = <u32>::sse_decode(deserializer);
        let mut var_scale = <f32>::sse_decode(deserializer);
        let mut var_backgroundRatio = <Option<f32>>::sse_decode(deserializer);
        let mut var_featheredRatio = <Option<f32>>::sse_decode(deserializer);
        let mut var_detectedBackground =
            <Option<crate::api::dto::ColorDto>>::sse_decode(deserializer);
        let mut var_notes = <Vec<String>>::sse_decode(deserializer);
        let mut var_warnings = <Vec<String>>::sse_decode(deserializer);
        return crate::api::dto::ProcessResultDto {
            bytes: var_bytes,
            width: var_width,
            height: var_height,
            format: var_format,
            format_name: var_formatName,
            source_format_name: var_sourceFormatName,
            quality: var_quality,
            scale: var_scale,
            background_ratio: var_backgroundRatio,
            feathered_ratio: var_featheredRatio,
            detected_background: var_detectedBackground,
            notes: var_notes,
            warnings: var_warnings,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for [u8; 3] {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::from_vec_to_array(inner);
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__dto__color_dto_to_rgb_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__image_api__core_version_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__init_app_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__image_api__list_presets_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__image_api__make_preview_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__image_api__probe_image_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__image_api__process_batch_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__image_api__process_image_impl(port, ptr, rust_vec_len, data_len),
        9 => {
            wire__crate__api__image_api__process_image_file_impl(port, ptr, rust_vec_len, data_len)
        }
        10 => wire__crate__api__image_api__standard_backgrounds_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::BackgroundChoiceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.color.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dto::BackgroundChoiceDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::BackgroundChoiceDto>
    for crate::api::dto::BackgroundChoiceDto
{
    fn into_into_dart(self) -> crate::api::dto::BackgroundChoiceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::BackgroundDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.color.into_into_dart().into_dart(),
            self.tolerance.into_into_dart().into_dart(),
            self.feather_px.into_into_dart().into_dart(),
            self.decontaminate.into_into_dart().into_dart(),
            self.edge_offset.into_into_dart().into_dart(),
            self.smooth_alpha.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dto::BackgroundDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::BackgroundDto>
    for crate::api::dto::BackgroundDto
{
    fn into_into_dart(self) -> crate::api::dto::BackgroundDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::BatchItemDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.bytes.into_into_dart().into_dart(),
            self.filename.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::BatchItemDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::BatchItemDto>
    for crate::api::dto::BatchItemDto
{
    fn into_into_dart(self) -> crate::api::dto::BatchItemDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::BatchProgressDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.index.into_into_dart().into_dart(),
            self.id.into_into_dart().into_dart(),
            self.done.into_into_dart().into_dart(),
            self.total.into_into_dart().into_dart(),
            self.succeeded.into_into_dart().into_dart(),
            self.failed.into_into_dart().into_dart(),
            self.result.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dto::BatchProgressDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::BatchProgressDto>
    for crate::api::dto::BatchProgressDto
{
    fn into_into_dart(self) -> crate::api::dto::BatchProgressDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::ColorDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.red.into_into_dart().into_dart(),
            self.green.into_into_dart().into_dart(),
            self.blue.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::ColorDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::ColorDto> for crate::api::dto::ColorDto {
    fn into_into_dart(self) -> crate::api::dto::ColorDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::CompressDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.target_bytes.into_into_dart().into_dart(),
            self.max_long_side.into_into_dart().into_dart(),
            self.quality_max.into_into_dart().into_dart(),
            self.quality_floor.into_into_dart().into_dart(),
            self.min_long_side.into_into_dart().into_dart(),
            self.jpeg_no_chroma_subsampling.into_into_dart().into_dart(),
            self.png_best_compression.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::CompressDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::CompressDto>
    for crate::api::dto::CompressDto
{
    fn into_into_dart(self) -> crate::api::dto::CompressDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::CropDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.preset_id.into_into_dart().into_dart(),
            self.rect.into_into_dart().into_dart(),
            self.out_width.into_into_dart().into_dart(),
            self.out_height.into_into_dart().into_dart(),
            self.vertical_anchor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::CropDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::CropDto> for crate::api::dto::CropDto {
    fn into_into_dart(self) -> crate::api::dto::CropDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::CropRectDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::CropRectDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::CropRectDto>
    for crate::api::dto::CropRectDto
{
    fn into_into_dart(self) -> crate::api::dto::CropRectDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::ImageInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.format_name.into_into_dart().into_dart(),
            self.frame_count.into_into_dart().into_dart(),
            self.byte_size.into_into_dart().into_dart(),
            self.source_supports_alpha.into_into_dart().into_dart(),
            self.source_supports_animation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::ImageInfoDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::ImageInfoDto>
    for crate::api::dto::ImageInfoDto
{
    fn into_into_dart(self) -> crate::api::dto::ImageInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::core::error::PicProError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::core::error::PicProError::UnknownFormat(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::UnsupportedFormat(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::Decode(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::Encode(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::Svg(field0) => {
                [4.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::Io(field0) => {
                [5.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::TargetUnreachable(field0) => {
                [6.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::core::error::PicProError::InvalidArgument(field0) => {
                [7.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::core::error::PicProError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::core::error::PicProError>
    for crate::core::error::PicProError
{
    fn into_into_dart(self) -> crate::core::error::PicProError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::PresetDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.category.into_into_dart().into_dart(),
            self.category_name.into_into_dart().into_dart(),
            self.width_mm.into_into_dart().into_dart(),
            self.height_mm.into_into_dart().into_dart(),
            self.width_px.into_into_dart().into_dart(),
            self.height_px.into_into_dart().into_dart(),
            self.dpi.into_into_dart().into_dart(),
            self.background_names.into_into_dart().into_dart(),
            self.background_colors.into_into_dart().into_dart(),
            self.note.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::PresetDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::PresetDto> for crate::api::dto::PresetDto {
    fn into_into_dart(self) -> crate::api::dto::PresetDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::ProcessOptionsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_format.into_into_dart().into_dart(),
            self.crop.into_into_dart().into_dart(),
            self.background.into_into_dart().into_dart(),
            self.compress.into_into_dart().into_dart(),
            self.flatten_color.into_into_dart().into_dart(),
            self.svg_render_width.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dto::ProcessOptionsDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::ProcessOptionsDto>
    for crate::api::dto::ProcessOptionsDto
{
    fn into_into_dart(self) -> crate::api::dto::ProcessOptionsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dto::ProcessResultDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.bytes.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.format_name.into_into_dart().into_dart(),
            self.source_format_name.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.scale.into_into_dart().into_dart(),
            self.background_ratio.into_into_dart().into_dart(),
            self.feathered_ratio.into_into_dart().into_dart(),
            self.detected_background.into_into_dart().into_dart(),
            self.notes.into_into_dart().into_dart(),
            self.warnings.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dto::ProcessResultDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::ProcessResultDto>
    for crate::api::dto::ProcessResultDto
{
    fn into_into_dart(self) -> crate::api::dto::ProcessResultDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::dto::BatchProgressDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::dto::BackgroundChoiceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <crate::api::dto::ColorDto>::sse_encode(self.color, serializer);
    }
}

impl SseEncode for crate::api::dto::BackgroundDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::dto::ColorDto>::sse_encode(self.color, serializer);
        <Option<f32>>::sse_encode(self.tolerance, serializer);
        <Option<u32>>::sse_encode(self.feather_px, serializer);
        <Option<bool>>::sse_encode(self.decontaminate, serializer);
        <Option<f32>>::sse_encode(self.edge_offset, serializer);
        <Option<bool>>::sse_encode(self.smooth_alpha, serializer);
    }
}

impl SseEncode for crate::api::dto::BatchItemDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <Vec<u8>>::sse_encode(self.bytes, serializer);
        <Option<String>>::sse_encode(self.filename, serializer);
    }
}

impl SseEncode for crate::api::dto::BatchProgressDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.index, serializer);
        <String>::sse_encode(self.id, serializer);
        <u32>::sse_encode(self.done, serializer);
        <u32>::sse_encode(self.total, serializer);
        <u32>::sse_encode(self.succeeded, serializer);
        <u32>::sse_encode(self.failed, serializer);
        <Option<crate::api::dto::ProcessResultDto>>::sse_encode(self.result, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::dto::ColorDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.red, serializer);
        <u32>::sse_encode(self.green, serializer);
        <u32>::sse_encode(self.blue, serializer);
    }
}

impl SseEncode for crate::api::dto::CompressDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<u64>>::sse_encode(self.target_bytes, serializer);
        <Option<u32>>::sse_encode(self.max_long_side, serializer);
        <Option<u32>>::sse_encode(self.quality_max, serializer);
        <Option<u32>>::sse_encode(self.quality_floor, serializer);
        <Option<u32>>::sse_encode(self.min_long_side, serializer);
        <Option<bool>>::sse_encode(self.jpeg_no_chroma_subsampling, serializer);
        <Option<bool>>::sse_encode(self.png_best_compression, serializer);
    }
}

impl SseEncode for crate::api::dto::CropDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.preset_id, serializer);
        <Option<crate::api::dto::CropRectDto>>::sse_encode(self.rect, serializer);
        <Option<u32>>::sse_encode(self.out_width, serializer);
        <Option<u32>>::sse_encode(self.out_height, serializer);
        <Option<f32>>::sse_encode(self.vertical_anchor, serializer);
    }
}

impl SseEncode for crate::api::dto::CropRectDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.x, serializer);
        <f32>::sse_encode(self.y, serializer);
        <f32>::sse_encode(self.width, serializer);
        <f32>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::dto::ImageInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <String>::sse_encode(self.format, serializer);
        <String>::sse_encode(self.format_name, serializer);
        <u32>::sse_encode(self.frame_count, serializer);
        <u64>::sse_encode(self.byte_size, serializer);
        <bool>::sse_encode(self.source_supports_alpha, serializer);
        <bool>::sse_encode(self.source_supports_animation, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::dto::BackgroundChoiceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::dto::BackgroundChoiceDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::dto::BatchItemDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::dto::BatchItemDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::dto::ColorDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::dto::ColorDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::dto::PresetDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::dto::PresetDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dto::BackgroundDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dto::BackgroundDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <bool>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dto::ColorDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dto::ColorDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dto::CompressDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dto::CompressDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dto::CropDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dto::CropDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dto::CropRectDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dto::CropRectDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dto::ProcessResultDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dto::ProcessResultDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::core::error::PicProError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::core::error::PicProError::UnknownFormat(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::UnsupportedFormat(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::Decode(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::Encode(field0) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::Svg(field0) => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::Io(field0) => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::TargetUnreachable(field0) => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::core::error::PicProError::InvalidArgument(field0) => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::dto::PresetDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.category, serializer);
        <String>::sse_encode(self.category_name, serializer);
        <f32>::sse_encode(self.width_mm, serializer);
        <f32>::sse_encode(self.height_mm, serializer);
        <u32>::sse_encode(self.width_px, serializer);
        <u32>::sse_encode(self.height_px, serializer);
        <u32>::sse_encode(self.dpi, serializer);
        <Vec<String>>::sse_encode(self.background_names, serializer);
        <Vec<crate::api::dto::ColorDto>>::sse_encode(self.background_colors, serializer);
        <String>::sse_encode(self.note, serializer);
    }
}

impl SseEncode for crate::api::dto::ProcessOptionsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.output_format, serializer);
        <Option<crate::api::dto::CropDto>>::sse_encode(self.crop, serializer);
        <Option<crate::api::dto::BackgroundDto>>::sse_encode(self.background, serializer);
        <Option<crate::api::dto::CompressDto>>::sse_encode(self.compress, serializer);
        <Option<crate::api::dto::ColorDto>>::sse_encode(self.flatten_color, serializer);
        <Option<u32>>::sse_encode(self.svg_render_width, serializer);
    }
}

impl SseEncode for crate::api::dto::ProcessResultDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.bytes, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <String>::sse_encode(self.format, serializer);
        <String>::sse_encode(self.format_name, serializer);
        <String>::sse_encode(self.source_format_name, serializer);
        <u32>::sse_encode(self.quality, serializer);
        <f32>::sse_encode(self.scale, serializer);
        <Option<f32>>::sse_encode(self.background_ratio, serializer);
        <Option<f32>>::sse_encode(self.feathered_ratio, serializer);
        <Option<crate::api::dto::ColorDto>>::sse_encode(self.detected_background, serializer);
        <Vec<String>>::sse_encode(self.notes, serializer);
        <Vec<String>>::sse_encode(self.warnings, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for [u8; 3] {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(
            {
                let boxed: Box<[_]> = Box::new(self);
                boxed.into_vec()
            },
            serializer,
        );
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
