// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dto.dart';
import 'api/image_api.dart';
import 'core/error.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 587978194;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'picpro_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<U8Array3> crateApiDtoColorDtoToRgb({required ColorDto that});

  Future<String> crateApiImageApiCoreVersion();

  Future<void> crateApiInitApp();

  Future<List<PresetDto>> crateApiImageApiListPresets();

  Future<Uint8List> crateApiImageApiMakePreview({
    required List<int> bytes,
    String? filename,
    required ProcessOptionsDto options,
    required int maxSide,
  });

  Future<ImageInfoDto> crateApiImageApiProbeImage({
    required List<int> bytes,
    String? filename,
  });

  Stream<BatchProgressDto> crateApiImageApiProcessBatch({
    required List<BatchItemDto> items,
    required ProcessOptionsDto options,
  });

  Future<ProcessResultDto> crateApiImageApiProcessImage({
    required List<int> bytes,
    String? filename,
    required ProcessOptionsDto options,
  });

  Future<ProcessResultDto> crateApiImageApiProcessImageFile({
    required String path,
    required ProcessOptionsDto options,
  });

  Future<List<BackgroundChoiceDto>> crateApiImageApiStandardBackgrounds();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<U8Array3> crateApiDtoColorDtoToRgb({required ColorDto that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_color_dto(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_3,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDtoColorDtoToRgbConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDtoColorDtoToRgbConstMeta =>
      const TaskConstMeta(debugName: "color_dto_to_rgb", argNames: ["that"]);

  @override
  Future<String> crateApiImageApiCoreVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageApiCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<PresetDto>> crateApiImageApiListPresets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_preset_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageApiListPresetsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiListPresetsConstMeta =>
      const TaskConstMeta(debugName: "list_presets", argNames: []);

  @override
  Future<Uint8List> crateApiImageApiMakePreview({
    required List<int> bytes,
    String? filename,
    required ProcessOptionsDto options,
    required int maxSide,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(filename, serializer);
          sse_encode_box_autoadd_process_options_dto(options, serializer);
          sse_encode_u_32(maxSide, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_pic_pro_error,
        ),
        constMeta: kCrateApiImageApiMakePreviewConstMeta,
        argValues: [bytes, filename, options, maxSide],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiMakePreviewConstMeta =>
      const TaskConstMeta(
        debugName: "make_preview",
        argNames: ["bytes", "filename", "options", "maxSide"],
      );

  @override
  Future<ImageInfoDto> crateApiImageApiProbeImage({
    required List<int> bytes,
    String? filename,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(filename, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_info_dto,
          decodeErrorData: sse_decode_pic_pro_error,
        ),
        constMeta: kCrateApiImageApiProbeImageConstMeta,
        argValues: [bytes, filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiProbeImageConstMeta => const TaskConstMeta(
    debugName: "probe_image",
    argNames: ["bytes", "filename"],
  );

  @override
  Stream<BatchProgressDto> crateApiImageApiProcessBatch({
    required List<BatchItemDto> items,
    required ProcessOptionsDto options,
  }) {
    final sink = RustStreamSink<BatchProgressDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_list_batch_item_dto(items, serializer);
            sse_encode_box_autoadd_process_options_dto(options, serializer);
            sse_encode_StreamSink_batch_progress_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiImageApiProcessBatchConstMeta,
          argValues: [items, options, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiImageApiProcessBatchConstMeta =>
      const TaskConstMeta(
        debugName: "process_batch",
        argNames: ["items", "options", "sink"],
      );

  @override
  Future<ProcessResultDto> crateApiImageApiProcessImage({
    required List<int> bytes,
    String? filename,
    required ProcessOptionsDto options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(filename, serializer);
          sse_encode_box_autoadd_process_options_dto(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_process_result_dto,
          decodeErrorData: sse_decode_pic_pro_error,
        ),
        constMeta: kCrateApiImageApiProcessImageConstMeta,
        argValues: [bytes, filename, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiProcessImageConstMeta =>
      const TaskConstMeta(
        debugName: "process_image",
        argNames: ["bytes", "filename", "options"],
      );

  @override
  Future<ProcessResultDto> crateApiImageApiProcessImageFile({
    required String path,
    required ProcessOptionsDto options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_process_options_dto(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_process_result_dto,
          decodeErrorData: sse_decode_pic_pro_error,
        ),
        constMeta: kCrateApiImageApiProcessImageFileConstMeta,
        argValues: [path, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiProcessImageFileConstMeta =>
      const TaskConstMeta(
        debugName: "process_image_file",
        argNames: ["path", "options"],
      );

  @override
  Future<List<BackgroundChoiceDto>> crateApiImageApiStandardBackgrounds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_background_choice_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageApiStandardBackgroundsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageApiStandardBackgroundsConstMeta =>
      const TaskConstMeta(debugName: "standard_backgrounds", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<BatchProgressDto> dco_decode_StreamSink_batch_progress_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BackgroundChoiceDto dco_decode_background_choice_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BackgroundChoiceDto(
      name: dco_decode_String(arr[0]),
      color: dco_decode_color_dto(arr[1]),
    );
  }

  @protected
  BackgroundDto dco_decode_background_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BackgroundDto(
      color: dco_decode_color_dto(arr[0]),
      tolerance: dco_decode_opt_box_autoadd_f_32(arr[1]),
      featherPx: dco_decode_opt_box_autoadd_u_32(arr[2]),
      decontaminate: dco_decode_opt_box_autoadd_bool(arr[3]),
      edgeOffset: dco_decode_opt_box_autoadd_f_32(arr[4]),
      smoothAlpha: dco_decode_opt_box_autoadd_bool(arr[5]),
    );
  }

  @protected
  BatchItemDto dco_decode_batch_item_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BatchItemDto(
      id: dco_decode_String(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
      filename: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  BatchProgressDto dco_decode_batch_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BatchProgressDto(
      index: dco_decode_u_32(arr[0]),
      id: dco_decode_String(arr[1]),
      done: dco_decode_u_32(arr[2]),
      total: dco_decode_u_32(arr[3]),
      succeeded: dco_decode_u_32(arr[4]),
      failed: dco_decode_u_32(arr[5]),
      result: dco_decode_opt_box_autoadd_process_result_dto(arr[6]),
      error: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BackgroundDto dco_decode_box_autoadd_background_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_background_dto(raw);
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ColorDto dco_decode_box_autoadd_color_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_color_dto(raw);
  }

  @protected
  CompressDto dco_decode_box_autoadd_compress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compress_dto(raw);
  }

  @protected
  CropDto dco_decode_box_autoadd_crop_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_crop_dto(raw);
  }

  @protected
  CropRectDto dco_decode_box_autoadd_crop_rect_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_crop_rect_dto(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ProcessOptionsDto dco_decode_box_autoadd_process_options_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_process_options_dto(raw);
  }

  @protected
  ProcessResultDto dco_decode_box_autoadd_process_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_process_result_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ColorDto dco_decode_color_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ColorDto(
      red: dco_decode_u_32(arr[0]),
      green: dco_decode_u_32(arr[1]),
      blue: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  CompressDto dco_decode_compress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CompressDto(
      targetBytes: dco_decode_opt_box_autoadd_u_64(arr[0]),
      maxLongSide: dco_decode_opt_box_autoadd_u_32(arr[1]),
      qualityMax: dco_decode_opt_box_autoadd_u_32(arr[2]),
      qualityFloor: dco_decode_opt_box_autoadd_u_32(arr[3]),
      minLongSide: dco_decode_opt_box_autoadd_u_32(arr[4]),
      jpegNoChromaSubsampling: dco_decode_opt_box_autoadd_bool(arr[5]),
      pngBestCompression: dco_decode_opt_box_autoadd_bool(arr[6]),
    );
  }

  @protected
  CropDto dco_decode_crop_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CropDto(
      presetId: dco_decode_opt_String(arr[0]),
      rect: dco_decode_opt_box_autoadd_crop_rect_dto(arr[1]),
      outWidth: dco_decode_opt_box_autoadd_u_32(arr[2]),
      outHeight: dco_decode_opt_box_autoadd_u_32(arr[3]),
      verticalAnchor: dco_decode_opt_box_autoadd_f_32(arr[4]),
    );
  }

  @protected
  CropRectDto dco_decode_crop_rect_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CropRectDto(
      x: dco_decode_f_32(arr[0]),
      y: dco_decode_f_32(arr[1]),
      width: dco_decode_f_32(arr[2]),
      height: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ImageInfoDto dco_decode_image_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ImageInfoDto(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      format: dco_decode_String(arr[2]),
      formatName: dco_decode_String(arr[3]),
      frameCount: dco_decode_u_32(arr[4]),
      byteSize: dco_decode_u_64(arr[5]),
      sourceSupportsAlpha: dco_decode_bool(arr[6]),
      sourceSupportsAnimation: dco_decode_bool(arr[7]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BackgroundChoiceDto> dco_decode_list_background_choice_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_background_choice_dto)
        .toList();
  }

  @protected
  List<BatchItemDto> dco_decode_list_batch_item_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_batch_item_dto).toList();
  }

  @protected
  List<ColorDto> dco_decode_list_color_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_color_dto).toList();
  }

  @protected
  List<PresetDto> dco_decode_list_preset_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_preset_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BackgroundDto? dco_decode_opt_box_autoadd_background_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_background_dto(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  ColorDto? dco_decode_opt_box_autoadd_color_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_color_dto(raw);
  }

  @protected
  CompressDto? dco_decode_opt_box_autoadd_compress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_compress_dto(raw);
  }

  @protected
  CropDto? dco_decode_opt_box_autoadd_crop_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_crop_dto(raw);
  }

  @protected
  CropRectDto? dco_decode_opt_box_autoadd_crop_rect_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_crop_rect_dto(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  ProcessResultDto? dco_decode_opt_box_autoadd_process_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_process_result_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PicProError dco_decode_pic_pro_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PicProError_UnknownFormat(dco_decode_String(raw[1]));
      case 1:
        return PicProError_UnsupportedFormat(dco_decode_String(raw[1]));
      case 2:
        return PicProError_Decode(dco_decode_String(raw[1]));
      case 3:
        return PicProError_Encode(dco_decode_String(raw[1]));
      case 4:
        return PicProError_Svg(dco_decode_String(raw[1]));
      case 5:
        return PicProError_Io(dco_decode_String(raw[1]));
      case 6:
        return PicProError_TargetUnreachable(dco_decode_String(raw[1]));
      case 7:
        return PicProError_InvalidArgument(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PresetDto dco_decode_preset_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return PresetDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      categoryName: dco_decode_String(arr[3]),
      widthMm: dco_decode_f_32(arr[4]),
      heightMm: dco_decode_f_32(arr[5]),
      widthPx: dco_decode_u_32(arr[6]),
      heightPx: dco_decode_u_32(arr[7]),
      dpi: dco_decode_u_32(arr[8]),
      backgroundNames: dco_decode_list_String(arr[9]),
      backgroundColors: dco_decode_list_color_dto(arr[10]),
      note: dco_decode_String(arr[11]),
    );
  }

  @protected
  ProcessOptionsDto dco_decode_process_options_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProcessOptionsDto(
      outputFormat: dco_decode_opt_String(arr[0]),
      crop: dco_decode_opt_box_autoadd_crop_dto(arr[1]),
      background: dco_decode_opt_box_autoadd_background_dto(arr[2]),
      compress: dco_decode_opt_box_autoadd_compress_dto(arr[3]),
      flattenColor: dco_decode_opt_box_autoadd_color_dto(arr[4]),
      svgRenderWidth: dco_decode_opt_box_autoadd_u_32(arr[5]),
    );
  }

  @protected
  ProcessResultDto dco_decode_process_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ProcessResultDto(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      format: dco_decode_String(arr[3]),
      formatName: dco_decode_String(arr[4]),
      sourceFormatName: dco_decode_String(arr[5]),
      quality: dco_decode_u_32(arr[6]),
      scale: dco_decode_f_32(arr[7]),
      backgroundRatio: dco_decode_opt_box_autoadd_f_32(arr[8]),
      featheredRatio: dco_decode_opt_box_autoadd_f_32(arr[9]),
      detectedBackground: dco_decode_opt_box_autoadd_color_dto(arr[10]),
      notes: dco_decode_list_String(arr[11]),
      warnings: dco_decode_list_String(arr[12]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array3 dco_decode_u_8_array_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array3(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<BatchProgressDto> sse_decode_StreamSink_batch_progress_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BackgroundChoiceDto sse_decode_background_choice_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_color = sse_decode_color_dto(deserializer);
    return BackgroundChoiceDto(name: var_name, color: var_color);
  }

  @protected
  BackgroundDto sse_decode_background_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_color = sse_decode_color_dto(deserializer);
    var var_tolerance = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_featherPx = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_decontaminate = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_edgeOffset = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_smoothAlpha = sse_decode_opt_box_autoadd_bool(deserializer);
    return BackgroundDto(
      color: var_color,
      tolerance: var_tolerance,
      featherPx: var_featherPx,
      decontaminate: var_decontaminate,
      edgeOffset: var_edgeOffset,
      smoothAlpha: var_smoothAlpha,
    );
  }

  @protected
  BatchItemDto sse_decode_batch_item_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_filename = sse_decode_opt_String(deserializer);
    return BatchItemDto(id: var_id, bytes: var_bytes, filename: var_filename);
  }

  @protected
  BatchProgressDto sse_decode_batch_progress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_done = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_succeeded = sse_decode_u_32(deserializer);
    var var_failed = sse_decode_u_32(deserializer);
    var var_result = sse_decode_opt_box_autoadd_process_result_dto(
      deserializer,
    );
    var var_error = sse_decode_opt_String(deserializer);
    return BatchProgressDto(
      index: var_index,
      id: var_id,
      done: var_done,
      total: var_total,
      succeeded: var_succeeded,
      failed: var_failed,
      result: var_result,
      error: var_error,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BackgroundDto sse_decode_box_autoadd_background_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_background_dto(deserializer));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  ColorDto sse_decode_box_autoadd_color_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_color_dto(deserializer));
  }

  @protected
  CompressDto sse_decode_box_autoadd_compress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compress_dto(deserializer));
  }

  @protected
  CropDto sse_decode_box_autoadd_crop_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_crop_dto(deserializer));
  }

  @protected
  CropRectDto sse_decode_box_autoadd_crop_rect_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_crop_rect_dto(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  ProcessOptionsDto sse_decode_box_autoadd_process_options_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_process_options_dto(deserializer));
  }

  @protected
  ProcessResultDto sse_decode_box_autoadd_process_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_process_result_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ColorDto sse_decode_color_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_red = sse_decode_u_32(deserializer);
    var var_green = sse_decode_u_32(deserializer);
    var var_blue = sse_decode_u_32(deserializer);
    return ColorDto(red: var_red, green: var_green, blue: var_blue);
  }

  @protected
  CompressDto sse_decode_compress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_targetBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_maxLongSide = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_qualityMax = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_qualityFloor = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_minLongSide = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_jpegNoChromaSubsampling = sse_decode_opt_box_autoadd_bool(
      deserializer,
    );
    var var_pngBestCompression = sse_decode_opt_box_autoadd_bool(deserializer);
    return CompressDto(
      targetBytes: var_targetBytes,
      maxLongSide: var_maxLongSide,
      qualityMax: var_qualityMax,
      qualityFloor: var_qualityFloor,
      minLongSide: var_minLongSide,
      jpegNoChromaSubsampling: var_jpegNoChromaSubsampling,
      pngBestCompression: var_pngBestCompression,
    );
  }

  @protected
  CropDto sse_decode_crop_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_presetId = sse_decode_opt_String(deserializer);
    var var_rect = sse_decode_opt_box_autoadd_crop_rect_dto(deserializer);
    var var_outWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_outHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_verticalAnchor = sse_decode_opt_box_autoadd_f_32(deserializer);
    return CropDto(
      presetId: var_presetId,
      rect: var_rect,
      outWidth: var_outWidth,
      outHeight: var_outHeight,
      verticalAnchor: var_verticalAnchor,
    );
  }

  @protected
  CropRectDto sse_decode_crop_rect_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    return CropRectDto(
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  ImageInfoDto sse_decode_image_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_formatName = sse_decode_String(deserializer);
    var var_frameCount = sse_decode_u_32(deserializer);
    var var_byteSize = sse_decode_u_64(deserializer);
    var var_sourceSupportsAlpha = sse_decode_bool(deserializer);
    var var_sourceSupportsAnimation = sse_decode_bool(deserializer);
    return ImageInfoDto(
      width: var_width,
      height: var_height,
      format: var_format,
      formatName: var_formatName,
      frameCount: var_frameCount,
      byteSize: var_byteSize,
      sourceSupportsAlpha: var_sourceSupportsAlpha,
      sourceSupportsAnimation: var_sourceSupportsAnimation,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BackgroundChoiceDto> sse_decode_list_background_choice_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BackgroundChoiceDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_background_choice_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<BatchItemDto> sse_decode_list_batch_item_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BatchItemDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_batch_item_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ColorDto> sse_decode_list_color_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ColorDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_color_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PresetDto> sse_decode_list_preset_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PresetDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_preset_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BackgroundDto? sse_decode_opt_box_autoadd_background_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_background_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ColorDto? sse_decode_opt_box_autoadd_color_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_color_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CompressDto? sse_decode_opt_box_autoadd_compress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_compress_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CropDto? sse_decode_opt_box_autoadd_crop_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_crop_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CropRectDto? sse_decode_opt_box_autoadd_crop_rect_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_crop_rect_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProcessResultDto? sse_decode_opt_box_autoadd_process_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_process_result_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PicProError sse_decode_pic_pro_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_UnknownFormat(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_UnsupportedFormat(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_Decode(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_Encode(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_Svg(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_Io(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_TargetUnreachable(var_field0);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return PicProError_InvalidArgument(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PresetDto sse_decode_preset_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_categoryName = sse_decode_String(deserializer);
    var var_widthMm = sse_decode_f_32(deserializer);
    var var_heightMm = sse_decode_f_32(deserializer);
    var var_widthPx = sse_decode_u_32(deserializer);
    var var_heightPx = sse_decode_u_32(deserializer);
    var var_dpi = sse_decode_u_32(deserializer);
    var var_backgroundNames = sse_decode_list_String(deserializer);
    var var_backgroundColors = sse_decode_list_color_dto(deserializer);
    var var_note = sse_decode_String(deserializer);
    return PresetDto(
      id: var_id,
      name: var_name,
      category: var_category,
      categoryName: var_categoryName,
      widthMm: var_widthMm,
      heightMm: var_heightMm,
      widthPx: var_widthPx,
      heightPx: var_heightPx,
      dpi: var_dpi,
      backgroundNames: var_backgroundNames,
      backgroundColors: var_backgroundColors,
      note: var_note,
    );
  }

  @protected
  ProcessOptionsDto sse_decode_process_options_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputFormat = sse_decode_opt_String(deserializer);
    var var_crop = sse_decode_opt_box_autoadd_crop_dto(deserializer);
    var var_background = sse_decode_opt_box_autoadd_background_dto(
      deserializer,
    );
    var var_compress = sse_decode_opt_box_autoadd_compress_dto(deserializer);
    var var_flattenColor = sse_decode_opt_box_autoadd_color_dto(deserializer);
    var var_svgRenderWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    return ProcessOptionsDto(
      outputFormat: var_outputFormat,
      crop: var_crop,
      background: var_background,
      compress: var_compress,
      flattenColor: var_flattenColor,
      svgRenderWidth: var_svgRenderWidth,
    );
  }

  @protected
  ProcessResultDto sse_decode_process_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_formatName = sse_decode_String(deserializer);
    var var_sourceFormatName = sse_decode_String(deserializer);
    var var_quality = sse_decode_u_32(deserializer);
    var var_scale = sse_decode_f_32(deserializer);
    var var_backgroundRatio = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_featheredRatio = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_detectedBackground = sse_decode_opt_box_autoadd_color_dto(
      deserializer,
    );
    var var_notes = sse_decode_list_String(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return ProcessResultDto(
      bytes: var_bytes,
      width: var_width,
      height: var_height,
      format: var_format,
      formatName: var_formatName,
      sourceFormatName: var_sourceFormatName,
      quality: var_quality,
      scale: var_scale,
      backgroundRatio: var_backgroundRatio,
      featheredRatio: var_featheredRatio,
      detectedBackground: var_detectedBackground,
      notes: var_notes,
      warnings: var_warnings,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array3 sse_decode_u_8_array_3(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array3(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_batch_progress_dto_Sse(
    RustStreamSink<BatchProgressDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_batch_progress_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_background_choice_dto(
    BackgroundChoiceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_color_dto(self.color, serializer);
  }

  @protected
  void sse_encode_background_dto(BackgroundDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_color_dto(self.color, serializer);
    sse_encode_opt_box_autoadd_f_32(self.tolerance, serializer);
    sse_encode_opt_box_autoadd_u_32(self.featherPx, serializer);
    sse_encode_opt_box_autoadd_bool(self.decontaminate, serializer);
    sse_encode_opt_box_autoadd_f_32(self.edgeOffset, serializer);
    sse_encode_opt_box_autoadd_bool(self.smoothAlpha, serializer);
  }

  @protected
  void sse_encode_batch_item_dto(BatchItemDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_opt_String(self.filename, serializer);
  }

  @protected
  void sse_encode_batch_progress_dto(
    BatchProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_u_32(self.done, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_u_32(self.succeeded, serializer);
    sse_encode_u_32(self.failed, serializer);
    sse_encode_opt_box_autoadd_process_result_dto(self.result, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_background_dto(
    BackgroundDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_background_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_color_dto(
    ColorDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_color_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_compress_dto(
    CompressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compress_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_crop_dto(CropDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crop_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_crop_rect_dto(
    CropRectDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crop_rect_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_process_options_dto(
    ProcessOptionsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_process_options_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_process_result_dto(
    ProcessResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_process_result_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_color_dto(ColorDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.red, serializer);
    sse_encode_u_32(self.green, serializer);
    sse_encode_u_32(self.blue, serializer);
  }

  @protected
  void sse_encode_compress_dto(CompressDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.targetBytes, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxLongSide, serializer);
    sse_encode_opt_box_autoadd_u_32(self.qualityMax, serializer);
    sse_encode_opt_box_autoadd_u_32(self.qualityFloor, serializer);
    sse_encode_opt_box_autoadd_u_32(self.minLongSide, serializer);
    sse_encode_opt_box_autoadd_bool(self.jpegNoChromaSubsampling, serializer);
    sse_encode_opt_box_autoadd_bool(self.pngBestCompression, serializer);
  }

  @protected
  void sse_encode_crop_dto(CropDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.presetId, serializer);
    sse_encode_opt_box_autoadd_crop_rect_dto(self.rect, serializer);
    sse_encode_opt_box_autoadd_u_32(self.outWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.outHeight, serializer);
    sse_encode_opt_box_autoadd_f_32(self.verticalAnchor, serializer);
  }

  @protected
  void sse_encode_crop_rect_dto(CropRectDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_image_info_dto(ImageInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_String(self.formatName, serializer);
    sse_encode_u_32(self.frameCount, serializer);
    sse_encode_u_64(self.byteSize, serializer);
    sse_encode_bool(self.sourceSupportsAlpha, serializer);
    sse_encode_bool(self.sourceSupportsAnimation, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_background_choice_dto(
    List<BackgroundChoiceDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_background_choice_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_batch_item_dto(
    List<BatchItemDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_batch_item_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_color_dto(
    List<ColorDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_color_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_preset_dto(
    List<PresetDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_preset_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_background_dto(
    BackgroundDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_background_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_color_dto(
    ColorDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_color_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_compress_dto(
    CompressDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_compress_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_crop_dto(
    CropDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_crop_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_crop_rect_dto(
    CropRectDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_crop_rect_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_process_result_dto(
    ProcessResultDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_process_result_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_pic_pro_error(PicProError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PicProError_UnknownFormat(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_UnsupportedFormat(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_Decode(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_Encode(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_Svg(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_Io(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_TargetUnreachable(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case PicProError_InvalidArgument(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_preset_dto(PresetDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.categoryName, serializer);
    sse_encode_f_32(self.widthMm, serializer);
    sse_encode_f_32(self.heightMm, serializer);
    sse_encode_u_32(self.widthPx, serializer);
    sse_encode_u_32(self.heightPx, serializer);
    sse_encode_u_32(self.dpi, serializer);
    sse_encode_list_String(self.backgroundNames, serializer);
    sse_encode_list_color_dto(self.backgroundColors, serializer);
    sse_encode_String(self.note, serializer);
  }

  @protected
  void sse_encode_process_options_dto(
    ProcessOptionsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.outputFormat, serializer);
    sse_encode_opt_box_autoadd_crop_dto(self.crop, serializer);
    sse_encode_opt_box_autoadd_background_dto(self.background, serializer);
    sse_encode_opt_box_autoadd_compress_dto(self.compress, serializer);
    sse_encode_opt_box_autoadd_color_dto(self.flattenColor, serializer);
    sse_encode_opt_box_autoadd_u_32(self.svgRenderWidth, serializer);
  }

  @protected
  void sse_encode_process_result_dto(
    ProcessResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_String(self.formatName, serializer);
    sse_encode_String(self.sourceFormatName, serializer);
    sse_encode_u_32(self.quality, serializer);
    sse_encode_f_32(self.scale, serializer);
    sse_encode_opt_box_autoadd_f_32(self.backgroundRatio, serializer);
    sse_encode_opt_box_autoadd_f_32(self.featheredRatio, serializer);
    sse_encode_opt_box_autoadd_color_dto(self.detectedBackground, serializer);
    sse_encode_list_String(self.notes, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_3(U8Array3 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
