// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/dto.dart';
import 'api/image_api.dart';
import 'core/error.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackgroundChoiceDto dco_decode_background_choice_dto(dynamic raw);

  @protected
  BackgroundDto dco_decode_background_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BackgroundDto dco_decode_box_autoadd_background_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ColorDto dco_decode_box_autoadd_color_dto(dynamic raw);

  @protected
  CompressDto dco_decode_box_autoadd_compress_dto(dynamic raw);

  @protected
  CropDto dco_decode_box_autoadd_crop_dto(dynamic raw);

  @protected
  CropRectDto dco_decode_box_autoadd_crop_rect_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  ProcessOptionsDto dco_decode_box_autoadd_process_options_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ColorDto dco_decode_color_dto(dynamic raw);

  @protected
  CompressDto dco_decode_compress_dto(dynamic raw);

  @protected
  CropDto dco_decode_crop_dto(dynamic raw);

  @protected
  CropRectDto dco_decode_crop_rect_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  ImageInfoDto dco_decode_image_info_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BackgroundChoiceDto> dco_decode_list_background_choice_dto(dynamic raw);

  @protected
  List<ColorDto> dco_decode_list_color_dto(dynamic raw);

  @protected
  List<PresetDto> dco_decode_list_preset_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BackgroundDto? dco_decode_opt_box_autoadd_background_dto(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ColorDto? dco_decode_opt_box_autoadd_color_dto(dynamic raw);

  @protected
  CompressDto? dco_decode_opt_box_autoadd_compress_dto(dynamic raw);

  @protected
  CropDto? dco_decode_opt_box_autoadd_crop_dto(dynamic raw);

  @protected
  CropRectDto? dco_decode_opt_box_autoadd_crop_rect_dto(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PicProError dco_decode_pic_pro_error(dynamic raw);

  @protected
  PresetDto dco_decode_preset_dto(dynamic raw);

  @protected
  ProcessOptionsDto dco_decode_process_options_dto(dynamic raw);

  @protected
  ProcessResultDto dco_decode_process_result_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array3 dco_decode_u_8_array_3(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackgroundChoiceDto sse_decode_background_choice_dto(
    SseDeserializer deserializer,
  );

  @protected
  BackgroundDto sse_decode_background_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BackgroundDto sse_decode_box_autoadd_background_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ColorDto sse_decode_box_autoadd_color_dto(SseDeserializer deserializer);

  @protected
  CompressDto sse_decode_box_autoadd_compress_dto(SseDeserializer deserializer);

  @protected
  CropDto sse_decode_box_autoadd_crop_dto(SseDeserializer deserializer);

  @protected
  CropRectDto sse_decode_box_autoadd_crop_rect_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  ProcessOptionsDto sse_decode_box_autoadd_process_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ColorDto sse_decode_color_dto(SseDeserializer deserializer);

  @protected
  CompressDto sse_decode_compress_dto(SseDeserializer deserializer);

  @protected
  CropDto sse_decode_crop_dto(SseDeserializer deserializer);

  @protected
  CropRectDto sse_decode_crop_rect_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  ImageInfoDto sse_decode_image_info_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BackgroundChoiceDto> sse_decode_list_background_choice_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ColorDto> sse_decode_list_color_dto(SseDeserializer deserializer);

  @protected
  List<PresetDto> sse_decode_list_preset_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BackgroundDto? sse_decode_opt_box_autoadd_background_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ColorDto? sse_decode_opt_box_autoadd_color_dto(SseDeserializer deserializer);

  @protected
  CompressDto? sse_decode_opt_box_autoadd_compress_dto(
    SseDeserializer deserializer,
  );

  @protected
  CropDto? sse_decode_opt_box_autoadd_crop_dto(SseDeserializer deserializer);

  @protected
  CropRectDto? sse_decode_opt_box_autoadd_crop_rect_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PicProError sse_decode_pic_pro_error(SseDeserializer deserializer);

  @protected
  PresetDto sse_decode_preset_dto(SseDeserializer deserializer);

  @protected
  ProcessOptionsDto sse_decode_process_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProcessResultDto sse_decode_process_result_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array3 sse_decode_u_8_array_3(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_background_choice_dto(
    BackgroundChoiceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_background_dto(BackgroundDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_background_dto(
    BackgroundDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_color_dto(
    ColorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_compress_dto(
    CompressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_crop_dto(CropDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_crop_rect_dto(
    CropRectDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_process_options_dto(
    ProcessOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_color_dto(ColorDto self, SseSerializer serializer);

  @protected
  void sse_encode_compress_dto(CompressDto self, SseSerializer serializer);

  @protected
  void sse_encode_crop_dto(CropDto self, SseSerializer serializer);

  @protected
  void sse_encode_crop_rect_dto(CropRectDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_image_info_dto(ImageInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_background_choice_dto(
    List<BackgroundChoiceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_color_dto(List<ColorDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_preset_dto(
    List<PresetDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_background_dto(
    BackgroundDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_color_dto(
    ColorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_compress_dto(
    CompressDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_crop_dto(
    CropDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_crop_rect_dto(
    CropRectDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pic_pro_error(PicProError self, SseSerializer serializer);

  @protected
  void sse_encode_preset_dto(PresetDto self, SseSerializer serializer);

  @protected
  void sse_encode_process_options_dto(
    ProcessOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_result_dto(
    ProcessResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_3(U8Array3 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
