// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class PicProError with _$PicProError implements FrbException {
  const PicProError._();

  /// 无法识别输入格式（魔数与扩展名都不匹配已知类型）
  const factory PicProError.unknownFormat(String field0) =
      PicProError_UnknownFormat;

  /// 输入声明为某格式但实际内容不符，或该格式不支持该操作
  const factory PicProError.unsupportedFormat(String field0) =
      PicProError_UnsupportedFormat;

  /// 解码失败
  const factory PicProError.decode(String field0) = PicProError_Decode;

  /// 编码失败
  const factory PicProError.encode(String field0) = PicProError_Encode;

  /// SVG 栅格化失败
  const factory PicProError.svg(String field0) = PicProError_Svg;

  /// 文件读写失败
  const factory PicProError.io(String field0) = PicProError_Io;

  /// 在给定约束（体积上限 / 分辨率下限）下无法达成目标，
  /// 属于「用户可调整参数解决」的失败，界面应提示放宽约束
  const factory PicProError.targetUnreachable(String field0) =
      PicProError_TargetUnreachable;

  /// 参数非法
  const factory PicProError.invalidArgument(String field0) =
      PicProError_InvalidArgument;
}
