// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 预设底色选项（名称 + 标准色值）。
class BackgroundChoiceDto {
  final String name;
  final ColorDto color;

  const BackgroundChoiceDto({required this.name, required this.color});

  @override
  int get hashCode => name.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackgroundChoiceDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          color == other.color;
}

/// 换背景参数。
class BackgroundDto {
  /// 目标底色
  final ColorDto color;

  /// 背景判定阈值 0~1，默认 0.12
  final double? tolerance;

  /// 软边过渡带宽度（像素），默认 2
  final int? featherPx;

  /// 是否做白底去污染，默认 true
  final bool? decontaminate;

  /// 边缘收放 -1~1，默认 0
  final double? edgeOffset;

  /// 是否平滑 alpha，默认 true
  final bool? smoothAlpha;

  const BackgroundDto({
    required this.color,
    this.tolerance,
    this.featherPx,
    this.decontaminate,
    this.edgeOffset,
    this.smoothAlpha,
  });

  @override
  int get hashCode =>
      color.hashCode ^
      tolerance.hashCode ^
      featherPx.hashCode ^
      decontaminate.hashCode ^
      edgeOffset.hashCode ^
      smoothAlpha.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackgroundDto &&
          runtimeType == other.runtimeType &&
          color == other.color &&
          tolerance == other.tolerance &&
          featherPx == other.featherPx &&
          decontaminate == other.decontaminate &&
          edgeOffset == other.edgeOffset &&
          smoothAlpha == other.smoothAlpha;
}

/// 批量处理输入项。
class BatchItemDto {
  /// 调用方自定义的稳定标识，用于把进度回报对应回列表行
  final String id;
  final Uint8List bytes;
  final String? filename;

  const BatchItemDto({required this.id, required this.bytes, this.filename});

  @override
  int get hashCode => id.hashCode ^ bytes.hashCode ^ filename.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bytes == other.bytes &&
          filename == other.filename;
}

/// 批量处理进度回报。
class BatchProgressDto {
  /// 该输入项在提交列表中的下标
  final int index;

  /// 调用方标识，原样回传
  final String id;

  /// 累计完成数（含成功与失败）
  final int done;

  /// 总任务数
  final int total;

  /// 累计成功数
  final int succeeded;

  /// 累计失败数
  final int failed;

  /// 成功时的处理结果
  final ProcessResultDto? result;

  /// 失败时的错误信息
  final String? error;

  const BatchProgressDto({
    required this.index,
    required this.id,
    required this.done,
    required this.total,
    required this.succeeded,
    required this.failed,
    this.result,
    this.error,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      id.hashCode ^
      done.hashCode ^
      total.hashCode ^
      succeeded.hashCode ^
      failed.hashCode ^
      result.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchProgressDto &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          id == other.id &&
          done == other.done &&
          total == other.total &&
          succeeded == other.succeeded &&
          failed == other.failed &&
          result == other.result &&
          error == other.error;
}

/// RGB 颜色。
class ColorDto {
  final int red;
  final int green;
  final int blue;

  const ColorDto({required this.red, required this.green, required this.blue});

  /// 转换为内核使用的三字节颜色，并夹紧到 0~255。
  ///
  /// Dart 侧传入越界值时不应导致崩溃，因此统一夹紧而非报错。
  Future<U8Array3> toRgb() =>
      RustLib.instance.api.crateApiDtoColorDtoToRgb(that: this);

  @override
  int get hashCode => red.hashCode ^ green.hashCode ^ blue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorDto &&
          runtimeType == other.runtimeType &&
          red == other.red &&
          green == other.green &&
          blue == other.blue;
}

/// 压缩参数。
class CompressDto {
  /// 体积上限（字节）
  final BigInt? targetBytes;

  /// 长边上限（等比，不放大）
  final int? maxLongSide;

  /// JPEG 质量上限，1~100，默认 95
  final int? qualityMax;

  /// 可接受的最低质量，默认 85
  final int? qualityFloor;

  /// 输出长边下限，默认 200
  final int? minLongSide;

  /// JPEG 是否禁用色度抽样（即 4:4:4），默认 true
  final bool? jpegNoChromaSubsampling;

  /// PNG 是否使用最高压缩级别，默认 true
  final bool? pngBestCompression;

  const CompressDto({
    this.targetBytes,
    this.maxLongSide,
    this.qualityMax,
    this.qualityFloor,
    this.minLongSide,
    this.jpegNoChromaSubsampling,
    this.pngBestCompression,
  });

  @override
  int get hashCode =>
      targetBytes.hashCode ^
      maxLongSide.hashCode ^
      qualityMax.hashCode ^
      qualityFloor.hashCode ^
      minLongSide.hashCode ^
      jpegNoChromaSubsampling.hashCode ^
      pngBestCompression.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressDto &&
          runtimeType == other.runtimeType &&
          targetBytes == other.targetBytes &&
          maxLongSide == other.maxLongSide &&
          qualityMax == other.qualityMax &&
          qualityFloor == other.qualityFloor &&
          minLongSide == other.minLongSide &&
          jpegNoChromaSubsampling == other.jpegNoChromaSubsampling &&
          pngBestCompression == other.pngBestCompression;
}

/// 裁剪参数。
class CropDto {
  /// 证件照规格 id，如 "size_1cun"。给出时会以规格像素作为输出尺寸
  final String? presetId;

  /// 归一化裁剪框。None 且给出 preset_id 时按规格比例自动构图
  final CropRectDto? rect;

  /// 目标输出宽度（与高度同时给出时缩放到精确像素）
  final int? outWidth;

  /// 目标输出高度
  final int? outHeight;

  /// 自动构图的纵向锚点，0~1
  final double? verticalAnchor;

  const CropDto({
    this.presetId,
    this.rect,
    this.outWidth,
    this.outHeight,
    this.verticalAnchor,
  });

  @override
  int get hashCode =>
      presetId.hashCode ^
      rect.hashCode ^
      outWidth.hashCode ^
      outHeight.hashCode ^
      verticalAnchor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CropDto &&
          runtimeType == other.runtimeType &&
          presetId == other.presetId &&
          rect == other.rect &&
          outWidth == other.outWidth &&
          outHeight == other.outHeight &&
          verticalAnchor == other.verticalAnchor;
}

/// 归一化裁剪框。
class CropRectDto {
  final double x;
  final double y;
  final double width;
  final double height;

  const CropRectDto({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CropRectDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}

/// 图片基础信息（探测用，不做完整解码）。
class ImageInfoDto {
  final int width;
  final int height;

  /// 规范格式名，如 "jpeg"
  final String format;

  /// 展示名，如 "JPEG"
  final String formatName;

  /// 帧数。非动画格式恒为 1
  final int frameCount;

  /// 输入字节数
  final BigInt byteSize;

  /// 源格式是否支持透明通道（按格式能力给出，非逐像素检测）
  final bool sourceSupportsAlpha;

  /// 源格式是否支持动画
  final bool sourceSupportsAnimation;

  const ImageInfoDto({
    required this.width,
    required this.height,
    required this.format,
    required this.formatName,
    required this.frameCount,
    required this.byteSize,
    required this.sourceSupportsAlpha,
    required this.sourceSupportsAnimation,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      formatName.hashCode ^
      frameCount.hashCode ^
      byteSize.hashCode ^
      sourceSupportsAlpha.hashCode ^
      sourceSupportsAnimation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfoDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          formatName == other.formatName &&
          frameCount == other.frameCount &&
          byteSize == other.byteSize &&
          sourceSupportsAlpha == other.sourceSupportsAlpha &&
          sourceSupportsAnimation == other.sourceSupportsAnimation;
}

/// 证件照规格预设。
class PresetDto {
  final String id;
  final String name;

  /// 分类规范名
  final String category;

  /// 分类展示名
  final String categoryName;
  final double widthMm;
  final double heightMm;
  final int widthPx;
  final int heightPx;
  final int dpi;

  /// 常用底色展示名
  final List<String> backgroundNames;

  /// 常用底色色值
  final List<ColorDto> backgroundColors;

  /// 备注（用途与额外限制）
  final String note;

  const PresetDto({
    required this.id,
    required this.name,
    required this.category,
    required this.categoryName,
    required this.widthMm,
    required this.heightMm,
    required this.widthPx,
    required this.heightPx,
    required this.dpi,
    required this.backgroundNames,
    required this.backgroundColors,
    required this.note,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      category.hashCode ^
      categoryName.hashCode ^
      widthMm.hashCode ^
      heightMm.hashCode ^
      widthPx.hashCode ^
      heightPx.hashCode ^
      dpi.hashCode ^
      backgroundNames.hashCode ^
      backgroundColors.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresetDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          category == other.category &&
          categoryName == other.categoryName &&
          widthMm == other.widthMm &&
          heightMm == other.heightMm &&
          widthPx == other.widthPx &&
          heightPx == other.heightPx &&
          dpi == other.dpi &&
          backgroundNames == other.backgroundNames &&
          backgroundColors == other.backgroundColors &&
          note == other.note;
}

/// 单张图片的完整处理参数。
class ProcessOptionsDto {
  /// 输出格式，如 "jpg"/"png"/"webp"；None 表示按源格式推断
  final String? outputFormat;
  final CropDto? crop;
  final BackgroundDto? background;
  final CompressDto? compress;

  /// 输出格式不支持透明通道时的压平底色，默认白色
  final ColorDto? flattenColor;

  /// 输入为 SVG 且未指定尺寸时的栅格化宽度，默认按 SVG 自带尺寸
  final int? svgRenderWidth;

  const ProcessOptionsDto({
    this.outputFormat,
    this.crop,
    this.background,
    this.compress,
    this.flattenColor,
    this.svgRenderWidth,
  });

  @override
  int get hashCode =>
      outputFormat.hashCode ^
      crop.hashCode ^
      background.hashCode ^
      compress.hashCode ^
      flattenColor.hashCode ^
      svgRenderWidth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessOptionsDto &&
          runtimeType == other.runtimeType &&
          outputFormat == other.outputFormat &&
          crop == other.crop &&
          background == other.background &&
          compress == other.compress &&
          flattenColor == other.flattenColor &&
          svgRenderWidth == other.svgRenderWidth;
}

/// 处理结果（处理失败时通过异常返回，因此此处字段恒为成功态）。
class ProcessResultDto {
  /// 输出文件字节
  final Uint8List bytes;
  final int width;
  final int height;

  /// 输出格式规范名
  final String format;

  /// 输出格式展示名
  final String formatName;

  /// 源格式展示名
  final String sourceFormatName;

  /// 最终质量（非质量格式为其质量上限值）
  final int quality;

  /// 最终缩放比例
  final double scale;

  /// 换背景时的背景占比
  final double? backgroundRatio;

  /// 换背景时的半透明过渡像素占比
  final double? featheredRatio;

  /// 换背景时检测到的原背景色
  final ColorDto? detectedBackground;

  /// 处理过程说明
  final List<String> notes;

  /// 需要用户注意的降级提示
  final List<String> warnings;

  const ProcessResultDto({
    required this.bytes,
    required this.width,
    required this.height,
    required this.format,
    required this.formatName,
    required this.sourceFormatName,
    required this.quality,
    required this.scale,
    this.backgroundRatio,
    this.featheredRatio,
    this.detectedBackground,
    required this.notes,
    required this.warnings,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      formatName.hashCode ^
      sourceFormatName.hashCode ^
      quality.hashCode ^
      scale.hashCode ^
      backgroundRatio.hashCode ^
      featheredRatio.hashCode ^
      detectedBackground.hashCode ^
      notes.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessResultDto &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          formatName == other.formatName &&
          sourceFormatName == other.sourceFormatName &&
          quality == other.quality &&
          scale == other.scale &&
          backgroundRatio == other.backgroundRatio &&
          featheredRatio == other.featheredRatio &&
          detectedBackground == other.detectedBackground &&
          notes == other.notes &&
          warnings == other.warnings;
}
